// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uixtjxnxymjdpkmszbdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpeHRqeG54eW1qZHBrbXN6YmR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODgwMTgsImV4cCI6MjA3Mzg2NDAxOH0.fQKCkc4j3xC_5JGKfTOYA05DEqxpOkXi5EhSdNogtXg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});